import { Language, Translations } from './types';

export const TRANSLATIONS: Translations = {
  [Language.EN]: {
    appTitle: "Noam Gold AI To-Do",
    addTask: "Add New Task",
    editTask: "Edit Task",
    deleteTask: "Delete Task",
    markDone: "Mark as Completed",
    markUndone: "Mark as Incomplete",
    subject: "Subject",
    description: "Description",
    dueDate: "Due Date & Time",
    flag: "Priority Flag",
    save: "Save Task",
    cancel: "Cancel",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    about: "About",
    exportAll: "Export Tasks",
    printAll: "Print List",
    search: "Search tasks...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "Send Feedback",
    overdue: "Overdue",
    dueIn: "Due in",
    completed: "Completed",
    share: "Share",
    userLogo: "User Logo",
    uploadLogo: "Upload Image",
    noTasks: "No tasks found. Add one to get started!",
    sortBy: "Sort By",
    sortManual: "Manual",
    sortDueDate: "Due Date",
    sortCreated: "Created Date",
    sortPriority: "Priority",
  },
  [Language.HE]: {
    appTitle: "נועם גולד AI משימות",
    addTask: "הוסף משימה חדשה",
    editTask: "ערוך משימה",
    deleteTask: "מחק משימה",
    markDone: "סמן כהושלם",
    markUndone: "סמן כלא הושלם",
    subject: "נושא",
    description: "תיאור",
    dueDate: "תאריך ושעה לביצוע",
    flag: "דגל עדיפות",
    save: "שמור משימה",
    cancel: "ביטול",
    settings: "הגדרות",
    language: "שפה",
    theme: "ערכת נושא",
    about: "אודות",
    exportAll: "ייצוא משימות",
    printAll: "הדפס רשימה",
    search: "חפש משימות...",
    copyright: "(C) נועם גולד AI 2025",
    feedback: "שלח משוב",
    overdue: "באיחור",
    dueIn: "מועד ב",
    completed: "הושלם",
    share: "שתף",
    userLogo: "לוגו משתמש",
    uploadLogo: "העלה תמונה",
    noTasks: "לא נמצאו משימות. הוסף אחת כדי להתחיל!",
    sortBy: "מיון לפי",
    sortManual: "ידני",
    sortDueDate: "תאריך יעד",
    sortCreated: "תאריך יצירה",
    sortPriority: "עדיפות",
  },
  [Language.ZH]: {
    appTitle: "Noam Gold AI 待办事项",
    addTask: "添加新任务",
    editTask: "编辑任务",
    deleteTask: "删除任务",
    markDone: "标记为完成",
    markUndone: "标记为未完成",
    subject: "主题",
    description: "描述",
    dueDate: "截止日期和时间",
    flag: "优先级标记",
    save: "保存任务",
    cancel: "取消",
    settings: "设置",
    language: "语言",
    theme: "主题",
    about: "关于",
    exportAll: "导出任务",
    printAll: "打印列表",
    search: "搜索任务...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "发送反馈",
    overdue: "逾期",
    dueIn: "到期时间",
    completed: "已完成",
    share: "分享",
    userLogo: "用户标志",
    uploadLogo: "上传图片",
    noTasks: "未找到任务。添加一个开始吧！",
    sortBy: "排序方式",
    sortManual: "手动",
    sortDueDate: "截止日期",
    sortCreated: "创建日期",
    sortPriority: "优先级",
  },
  [Language.RU]: {
    appTitle: "Noam Gold AI Задачи",
    addTask: "Добавить задачу",
    editTask: "Редактировать задачу",
    deleteTask: "Удалить задачу",
    markDone: "Отметить как выполненное",
    markUndone: "Отметить как невыполненное",
    subject: "Тема",
    description: "Описание",
    dueDate: "Срок выполнения",
    flag: "Флаг приоритета",
    save: "Сохранить",
    cancel: "Отмена",
    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    about: "О приложении",
    exportAll: "Экспорт задач",
    printAll: "Печать списка",
    search: "Поиск...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "Обратная связь",
    overdue: "Просрочено",
    dueIn: "Истекает через",
    completed: "Выполнено",
    share: "Поделиться",
    userLogo: "Логотип пользователя",
    uploadLogo: "Загрузить изображение",
    noTasks: "Задач нет. Добавьте первую!",
    sortBy: "Сортировка",
    sortManual: "Вручную",
    sortDueDate: "Срок",
    sortCreated: "Дата создания",
    sortPriority: "Приоритет",
  },
  [Language.HI]: {
    appTitle: "Noam Gold AI टू-डू",
    addTask: "नया कार्य जोड़ें",
    editTask: "कार्य संपादित करें",
    deleteTask: "कार्य हटाएं",
    markDone: "पूर्ण के रूप में चिह्नित करें",
    markUndone: "अपूर्ण के रूप में चिह्नित करें",
    subject: "विषय",
    description: "विवरण",
    dueDate: "नियत तारीख और समय",
    flag: "प्राथमिकता ध्वज",
    save: "कार्य सहेजें",
    cancel: "रद्द करें",
    settings: "सेटिंग्स",
    language: "भाषा",
    theme: "थीम",
    about: "के बारे में",
    exportAll: "कार्य निर्यात करें",
    printAll: "सूची प्रिंट करें",
    search: "खोज...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "प्रतिक्रिया भेजें",
    overdue: "अतिदेय",
    dueIn: "में देय",
    completed: "पूर्ण",
    share: "साझा करें",
    userLogo: "उपयोगकर्ता लोगो",
    uploadLogo: "छवि अपलोड करें",
    noTasks: "कोई कार्य नहीं मिला। शुरू करने के लिए एक जोड़ें!",
    sortBy: "क्रमबद्ध करें",
    sortManual: "मैनुअल",
    sortDueDate: "नियत तिथि",
    sortCreated: "बनाई गई तिथि",
    sortPriority: "प्राथमिकता",
  },
  [Language.ES]: {
    appTitle: "Noam Gold AI Tareas",
    addTask: "Añadir Tarea",
    editTask: "Editar Tarea",
    deleteTask: "Eliminar Tarea",
    markDone: "Marcar como Completada",
    markUndone: "Marcar como Incompleta",
    subject: "Asunto",
    description: "Descripción",
    dueDate: "Fecha y Hora de Vencimiento",
    flag: "Bandera de Prioridad",
    save: "Guardar Tarea",
    cancel: "Cancelar",
    settings: "Configuración",
    language: "Idioma",
    theme: "Tema",
    about: "Acerca de",
    exportAll: "Exportar Tareas",
    printAll: "Imprimir Lista",
    search: "Buscar tareas...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "Enviar Comentarios",
    overdue: "Vencido",
    dueIn: "Vence en",
    completed: "Completado",
    share: "Compartir",
    userLogo: "Logotipo de Usuario",
    uploadLogo: "Subir Imagen",
    noTasks: "No se encontraron tareas. ¡Añade una para empezar!",
    sortBy: "Ordenar por",
    sortManual: "Manual",
    sortDueDate: "Fecha de Vencimiento",
    sortCreated: "Fecha de Creación",
    sortPriority: "Prioridad",
  },
  [Language.DE]: {
    appTitle: "Noam Gold AI Aufgaben",
    addTask: "Aufgabe hinzufügen",
    editTask: "Aufgabe bearbeiten",
    deleteTask: "Aufgabe löschen",
    markDone: "Als erledigt markieren",
    markUndone: "Als unerledigt markieren",
    subject: "Betreff",
    description: "Beschreibung",
    dueDate: "Fälligkeitsdatum & Zeit",
    flag: "Prioritätsflagge",
    save: "Aufgabe speichern",
    cancel: "Abbrechen",
    settings: "Einstellungen",
    language: "Sprache",
    theme: "Thema",
    about: "Über",
    exportAll: "Aufgaben exportieren",
    printAll: "Liste drucken",
    search: "Suchen...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "Feedback senden",
    overdue: "Überfällig",
    dueIn: "Fällig in",
    completed: "Abgeschlossen",
    share: "Teilen",
    userLogo: "Benutzerlogo",
    uploadLogo: "Bild hochladen",
    noTasks: "Keine Aufgaben gefunden. Füge eine hinzu!",
    sortBy: "Sortieren nach",
    sortManual: "Manuell",
    sortDueDate: "Fälligkeitsdatum",
    sortCreated: "Erstellungsdatum",
    sortPriority: "Priorität",
  },
  [Language.FR]: {
    appTitle: "Noam Gold AI Tâches",
    addTask: "Ajouter une tâche",
    editTask: "Modifier la tâche",
    deleteTask: "Supprimer la tâche",
    markDone: "Marquer comme terminé",
    markUndone: "Marquer comme non terminé",
    subject: "Sujet",
    description: "Description",
    dueDate: "Date d'échéance",
    flag: "Drapeau de priorité",
    save: "Enregistrer",
    cancel: "Annuler",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    about: "À propos",
    exportAll: "Exporter les tâches",
    printAll: "Imprimer la liste",
    search: "Rechercher...",
    copyright: "(C) Noam Gold AI 2025",
    feedback: "Envoyer des commentaires",
    overdue: "En retard",
    dueIn: "Dû dans",
    completed: "Terminé",
    share: "Partager",
    userLogo: "Logo utilisateur",
    uploadLogo: "Télécharger une image",
    noTasks: "Aucune tâche trouvée. Ajoutez-en une pour commencer !",
    sortBy: "Trier par",
    sortManual: "Manuel",
    sortDueDate: "Date d'échéance",
    sortCreated: "Date de création",
    sortPriority: "Priorité",
  },
};

export const FLAG_COLORS = [
  '#ef4444', // Red
  '#f97316', // Orange
  '#eab308', // Yellow
  '#22c55e', // Green
  '#3b82f6', // Blue
  '#a855f7', // Purple
  '#ec4899', // Pink
  '#6b7280', // Gray
];